name: Deploy

on:
  workflow_dispatch:
  repository_dispatch:
    types: [notion-post-updated]

jobs:
  curl:
    name: Kick deploy hook
    runs-on: ubuntu-latest
    steps:
      - name: curl
        run: curl -X POST '${{ secrets.DEPLOY_HOOK_URL }}'
